name: Build VM Disk Image

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.version }} ${{ matrix.architecture.name }}
    runs-on: ubuntu-latest
    container: alpine:edge
    strategy:
        fail-fast: false
        matrix:
          version:
            - '13.4'
            - '14.2'

          architecture:
            - name: x86-64
              qemu: x86_64

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          apk add --no-cache \
            curl \
            qemu-img \
            "qemu-system-${{ matrix.architecture.qemu }}"

      - uses: hashicorp/setup-packer@main
        with:
          version: "1.9.1"

      - name: Build Image
        if: '!matrix.copy_from_previous_release'
        env:
          PACKER_LOG: 1
        run: |
          ./build.sh '${{ matrix.version }}' '${{ matrix.architecture.name }}' \
            -var 'headless=true'

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: FreeBSD ${{ github.ref_name }}
          draft: true
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
